refactored makefile, added suppor to output simple lexicon that can be read by analiticcl

diff --git a/experiments/Makefile b/experiments/Makefile
--- a/experiments/Makefile
+++ b/experiments/Makefile
@@ -1,43 +1,60 @@
 REPOROOT := $(shell git rev-parse --show-toplevel)
 DATADIR =
 
-all.txt: datadir
+
+# Indices:
+
+htr.index:
+ifeq ($(strip $(DATADIR)),)
+	@echo "Usage Error: Data directory required, please specify a DATADIR=/path/to/datadir argument" >&2
+	@false
+endif
+	#An index of all HTR-files
+	echo "" > htr.index
+	cat "$(REPOROOT)/resources/werkvoorraad.csv" | grep -E ";HTR" | awk -F ';' '{ print $$4"" }' | xargs -L 1 -I"{}" find "$(DATADIR)/{}" -name "*.xml" >> htr.index || [ -s htr.index ]
+
+groundtruth.index:
+ifeq ($(strip $(DATADIR)),)
+	@echo "Usage Error: Data directory required, please specify a DATADIR=/path/to/datadir argument" >&2
+	@false
+endif
+	#An index of all groundtruth-files
+	echo "" > groundtruth.index
+	cat "$(REPOROOT)/resources/werkvoorraad.csv" | grep -E ";GT" | awk -F ';' '{ print $$4"" }' | xargs -L 1 -I"{}" find "$(DATADIR)/{}" -name "*.xml" >> groundtruth.index || [ -s groundtruth.index ]
+
+# Extracted text:
+
+all.txt:
+ifeq ($(strip $(DATADIR)),)
+	@echo "Usage Error: Data directory required, please specify a DATADIR=/path/to/datadir argument" >&2
+	@false
+endif
 	#All text extracted from the data (irregardless of whether it is HTR or ground-truth (GT))
 	find "$(DATADIR)" -name "*.xml" | xargs "$(REPOROOT)/scripts/extract-text.py" | "$(REPOROOT)/scripts/dehyphenize.py" > all.txt
 
-all.tok.txt:  all.txt
-	#Tokenised version
-	ucto -L nld-historical -m -n all.txt all.tok.txt
+%.txt: %.index
+	cat $< | xargs "$(REPOROOT)/scripts/extract-text.py" | "$(REPOROOT)/scripts/dehyphenize.py" > $@
 
-htr.txt: htr.index
-	cat htr.index | xargs "$(REPOROOT)/scripts/extract-text.py" | "$(REPOROOT)/scripts/dehyphenize.py" > htr.txt
+%.tok.txt:  %.txt
+	#Tokenised version (may not be very accurate)
+	ucto -L nld-historical -m -n $< $@
 
-htr.tok.txt:  htr.txt
-	#Tokenised version of HTR (may not be very accurate)
-	ucto -L nld-historical -m -n htr.txt htr.tok.txt
+# Pattern models and extracted (decoded) lexicons:
 
-groundtruth.txt: groundtruth.index
-	#Tokenised version of groond truth (may not be very accurate)
-	cat groundtruth.index | xargs "$(REPOROOT)/scripts/extract-text.py" | "$(REPOROOT)/scripts/dehyphenize.py" > groundtruth.txt
+%.colibri.patternmodel: %.colibri.cls %.colibri.dat
+	colibri-patternmodeller -u -l 5 -t 2 -f $*.colibri.dat -c $*.colibri.cls --outputmodel $@
 
-groundtruth.tok.txt:  groundtruth.txt
-	#Tokenised version
-	ucto -L nld-historical -m -n groundtruth.txt groundtruth.tok.txt
+%.tok.colibri.cls: %.tok.txt
+	colibri-classencode $<
 
-htr.index: datadir
-	echo "" > htr.index
-	cat "$(REPOROOT)/resources/werkvoorraad.csv" | grep -E ";HTR" | awk -F ';' '{ print $$4"" }' | xargs -L 1 -I"{}" find "$(DATADIR)/{}" -name "*.xml" >> htr.index || [ -s htr.list ]
+%.tok.colibri.dat: %.tok.txt
+	colibri-classencode $<
 
-groundtruth.index: datadir
-	echo "" > groundtruth.index
-	cat "$(REPOROOT)/resources/werkvoorraad.csv" | grep -E ";GT" | awk -F ';' '{ print $$4"" }' | xargs -L 1 -I"{}" find "$(DATADIR)/{}" -name "*.xml" >> groundtruth.index || [ -s groundtruth.list ]
+%.lexicon.tsv: %.colibri.patternmodel %.colibri.cls
+	colibri-patternmodeller -u -i $*.colibri.patternmodel -c $*.colibri.cls --print -l 1 -t 2 | tail --lines="+2" | sort -r -n -k 2 | cut -f 1,2 > $@
 
-datadir:
-ifeq ($(strip $(DATADIR)),)
-	@echo "Usage Error: Data directory required, please specify a DATADIR=/path/to/datadir argument" >&2
-	@exit 2
-endif
 
+.PHONY: checkdeps
 checkdeps:
 	which cut
 	which find
